searcher:
  host: 0.0.0.0
  port: 8000
  loop: asyncio
  workers: 4 # change it accordingly to the server requirements
model:
  host: localhost
  port: 8001
  reload: true
  loop: asyncio
  workers: 1 # model runs on it. incrementing this will increase memory usage significantly