site_name: ViZearch Documentation
site_url: ""
site_description: "Comprehensive documentation for the ViZearch Semantic Search Platform"
site_author: "Doddapaneni Udith, Vishnu Shreeram, Dhruvadeep Malakar"
repo_url: https://github.com/your-username/SemanticSearch
repo_name: SemanticSearch
edit_uri: ""

# Theme configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png

# Navigation structure
nav:
  - Home: index.md
  - Introduction:
      - Overview: introduction.md
  - Architecture:
      - System Overview: architecture.md
  - Technical Details:
      - details: technical.md
  - Setup:
      - Prerequisites: setup.md
  - API Reference:
      - overview : api.md
  - About:
      - Team: about.md
  - Locust:
      - Locust: locust.md
# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true
      title: On this page
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
